apiVersion: v2
name: tracepod
description: eBPF container file profiler for Kubernetes — sensor DaemonSet
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - ebpf
  - security
  - container
  - hardening
  - profiling
home: https://github.com/tracepod/tracepod
sources:
  - https://github.com/tracepod/tracepod
maintainers:
  - name: Tracepod
    url: https://github.com/tracepod/tracepod
