// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadOpenat returns the embedded CollectionSpec for openat.
func loadOpenat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpenatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load openat: %w", err)
	}

	return spec, err
}

// loadOpenatObjects loads openat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*openatObjects
//	*openatPrograms
//	*openatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpenatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpenat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// openatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openatSpecs struct {
	openatProgramSpecs
	openatMapSpecs
	openatVariableSpecs
}

// openatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openatProgramSpecs struct {
	KprobeExecve *ebpf.ProgramSpec `ebpf:"kprobe_execve"`
	KprobeMmap   *ebpf.ProgramSpec `ebpf:"kprobe_mmap"`
	KprobeOpenat *ebpf.ProgramSpec `ebpf:"kprobe_openat"`
}

// openatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openatMapSpecs struct {
	AllowedCgroups *ebpf.MapSpec `ebpf:"allowed_cgroups"`
	Events         *ebpf.MapSpec `ebpf:"events"`
}

// openatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openatVariableSpecs struct {
}

// openatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type openatObjects struct {
	openatPrograms
	openatMaps
	openatVariables
}

func (o *openatObjects) Close() error {
	return _OpenatClose(
		&o.openatPrograms,
		&o.openatMaps,
	)
}

// openatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type openatMaps struct {
	AllowedCgroups *ebpf.Map `ebpf:"allowed_cgroups"`
	Events         *ebpf.Map `ebpf:"events"`
}

func (m *openatMaps) Close() error {
	return _OpenatClose(
		m.AllowedCgroups,
		m.Events,
	)
}

// openatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type openatVariables struct {
}

// openatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type openatPrograms struct {
	KprobeExecve *ebpf.Program `ebpf:"kprobe_execve"`
	KprobeMmap   *ebpf.Program `ebpf:"kprobe_mmap"`
	KprobeOpenat *ebpf.Program `ebpf:"kprobe_openat"`
}

func (p *openatPrograms) Close() error {
	return _OpenatClose(
		p.KprobeExecve,
		p.KprobeMmap,
		p.KprobeOpenat,
	)
}

func _OpenatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openat_arm64_bpfel.o
var _OpenatBytes []byte
